/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './modules/__root'
import { Route as DataServiceConfigurationProviderRouteImport } from './modules/data-service-configuration/_provider'
import { Route as DataServiceConfigurationProviderConfigIdProviderRouteImport } from './modules/data-service-configuration/_provider/$configId/_provider'
import { Route as DataServiceConfigurationProviderConfigIdProviderEditProviderRouteImport } from './modules/data-service-configuration/_provider/$configId/_provider/edit/_provider'

const IndexLazyRouteImport = createFileRoute('/')()
const DataServiceConfigurationProviderIndexLazyRouteImport = createFileRoute(
    '/data-service-configuration/_provider/'
)()
const DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRouteImport =
    createFileRoute(
        '/data-service-configuration/_provider/$configId/validation-logs/'
    )()
const DataServiceConfigurationProviderConfigIdProviderIndexLazyRouteImport =
    createFileRoute(
        '/data-service-configuration/_provider/$configId/_provider/'
    )()
const DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRouteImport =
    createFileRoute(
        '/data-service-configuration/_provider/$configId/_provider/edit/_provider/'
    )()

const IndexLazyRoute = IndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./modules/index.lazy').then((d) => d.Route))
const DataServiceConfigurationProviderRoute =
    DataServiceConfigurationProviderRouteImport.update({
        id: '/data-service-configuration/_provider',
        path: '/data-service-configuration',
        getParentRoute: () => rootRouteImport,
    } as any)
const DataServiceConfigurationProviderIndexLazyRoute =
    DataServiceConfigurationProviderIndexLazyRouteImport.update({
        id: '/',
        path: '/',
        getParentRoute: () => DataServiceConfigurationProviderRoute,
    } as any).lazy(() =>
        import('./modules/data-service-configuration/_provider/index.lazy').then(
            (d) => d.Route
        )
    )
const DataServiceConfigurationProviderConfigIdProviderRoute =
    DataServiceConfigurationProviderConfigIdProviderRouteImport.update({
        id: '/$configId/_provider',
        path: '/$configId',
        getParentRoute: () => DataServiceConfigurationProviderRoute,
    } as any)
const DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute =
    DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRouteImport.update(
        {
            id: '/$configId/validation-logs/',
            path: '/$configId/validation-logs/',
            getParentRoute: () => DataServiceConfigurationProviderRoute,
        } as any
    ).lazy(() =>
        import('./modules/data-service-configuration/_provider/$configId/validation-logs/index.lazy').then(
            (d) => d.Route
        )
    )
const DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute =
    DataServiceConfigurationProviderConfigIdProviderIndexLazyRouteImport.update(
        {
            id: '/',
            path: '/',
            getParentRoute: () =>
                DataServiceConfigurationProviderConfigIdProviderRoute,
        } as any
    ).lazy(() =>
        import('./modules/data-service-configuration/_provider/$configId/_provider/index.lazy').then(
            (d) => d.Route
        )
    )
const DataServiceConfigurationProviderConfigIdProviderEditProviderRoute =
    DataServiceConfigurationProviderConfigIdProviderEditProviderRouteImport.update(
        {
            id: '/edit/_provider',
            path: '/edit',
            getParentRoute: () =>
                DataServiceConfigurationProviderConfigIdProviderRoute,
        } as any
    )
const DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute =
    DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRouteImport.update(
        {
            id: '/',
            path: '/',
            getParentRoute: () =>
                DataServiceConfigurationProviderConfigIdProviderEditProviderRoute,
        } as any
    ).lazy(() =>
        import('./modules/data-service-configuration/_provider/$configId/_provider/edit/_provider/index.lazy').then(
            (d) => d.Route
        )
    )

export interface FileRoutesByFullPath {
    '/': typeof IndexLazyRoute
    '/data-service-configuration': typeof DataServiceConfigurationProviderRouteWithChildren
    '/data-service-configuration/': typeof DataServiceConfigurationProviderIndexLazyRoute
    '/data-service-configuration/$configId': typeof DataServiceConfigurationProviderConfigIdProviderRouteWithChildren
    '/data-service-configuration/$configId/': typeof DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute
    '/data-service-configuration/$configId/validation-logs/': typeof DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute
    '/data-service-configuration/$configId/edit': typeof DataServiceConfigurationProviderConfigIdProviderEditProviderRouteWithChildren
    '/data-service-configuration/$configId/edit/': typeof DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute
}
export interface FileRoutesByTo {
    '/': typeof IndexLazyRoute
    '/data-service-configuration': typeof DataServiceConfigurationProviderIndexLazyRoute
    '/data-service-configuration/$configId': typeof DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute
    '/data-service-configuration/$configId/validation-logs': typeof DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute
    '/data-service-configuration/$configId/edit': typeof DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/': typeof IndexLazyRoute
    '/data-service-configuration/_provider': typeof DataServiceConfigurationProviderRouteWithChildren
    '/data-service-configuration/_provider/': typeof DataServiceConfigurationProviderIndexLazyRoute
    '/data-service-configuration/_provider/$configId/_provider': typeof DataServiceConfigurationProviderConfigIdProviderRouteWithChildren
    '/data-service-configuration/_provider/$configId/_provider/': typeof DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute
    '/data-service-configuration/_provider/$configId/validation-logs/': typeof DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute
    '/data-service-configuration/_provider/$configId/_provider/edit/_provider': typeof DataServiceConfigurationProviderConfigIdProviderEditProviderRouteWithChildren
    '/data-service-configuration/_provider/$configId/_provider/edit/_provider/': typeof DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | '/'
        | '/data-service-configuration'
        | '/data-service-configuration/'
        | '/data-service-configuration/$configId'
        | '/data-service-configuration/$configId/'
        | '/data-service-configuration/$configId/validation-logs/'
        | '/data-service-configuration/$configId/edit'
        | '/data-service-configuration/$configId/edit/'
    fileRoutesByTo: FileRoutesByTo
    to:
        | '/'
        | '/data-service-configuration'
        | '/data-service-configuration/$configId'
        | '/data-service-configuration/$configId/validation-logs'
        | '/data-service-configuration/$configId/edit'
    id:
        | '__root__'
        | '/'
        | '/data-service-configuration/_provider'
        | '/data-service-configuration/_provider/'
        | '/data-service-configuration/_provider/$configId/_provider'
        | '/data-service-configuration/_provider/$configId/_provider/'
        | '/data-service-configuration/_provider/$configId/validation-logs/'
        | '/data-service-configuration/_provider/$configId/_provider/edit/_provider'
        | '/data-service-configuration/_provider/$configId/_provider/edit/_provider/'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexLazyRoute: typeof IndexLazyRoute
    DataServiceConfigurationProviderRoute: typeof DataServiceConfigurationProviderRouteWithChildren
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexLazyRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/data-service-configuration/_provider': {
            id: '/data-service-configuration/_provider'
            path: '/data-service-configuration'
            fullPath: '/data-service-configuration'
            preLoaderRoute: typeof DataServiceConfigurationProviderRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/data-service-configuration/_provider/': {
            id: '/data-service-configuration/_provider/'
            path: '/'
            fullPath: '/data-service-configuration/'
            preLoaderRoute: typeof DataServiceConfigurationProviderIndexLazyRouteImport
            parentRoute: typeof DataServiceConfigurationProviderRoute
        }
        '/data-service-configuration/_provider/$configId/_provider': {
            id: '/data-service-configuration/_provider/$configId/_provider'
            path: '/$configId'
            fullPath: '/data-service-configuration/$configId'
            preLoaderRoute: typeof DataServiceConfigurationProviderConfigIdProviderRouteImport
            parentRoute: typeof DataServiceConfigurationProviderRoute
        }
        '/data-service-configuration/_provider/$configId/validation-logs/': {
            id: '/data-service-configuration/_provider/$configId/validation-logs/'
            path: '/$configId/validation-logs'
            fullPath: '/data-service-configuration/$configId/validation-logs/'
            preLoaderRoute: typeof DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRouteImport
            parentRoute: typeof DataServiceConfigurationProviderRoute
        }
        '/data-service-configuration/_provider/$configId/_provider/': {
            id: '/data-service-configuration/_provider/$configId/_provider/'
            path: '/'
            fullPath: '/data-service-configuration/$configId/'
            preLoaderRoute: typeof DataServiceConfigurationProviderConfigIdProviderIndexLazyRouteImport
            parentRoute: typeof DataServiceConfigurationProviderConfigIdProviderRoute
        }
        '/data-service-configuration/_provider/$configId/_provider/edit/_provider': {
            id: '/data-service-configuration/_provider/$configId/_provider/edit/_provider'
            path: '/edit'
            fullPath: '/data-service-configuration/$configId/edit'
            preLoaderRoute: typeof DataServiceConfigurationProviderConfigIdProviderEditProviderRouteImport
            parentRoute: typeof DataServiceConfigurationProviderConfigIdProviderRoute
        }
        '/data-service-configuration/_provider/$configId/_provider/edit/_provider/': {
            id: '/data-service-configuration/_provider/$configId/_provider/edit/_provider/'
            path: '/'
            fullPath: '/data-service-configuration/$configId/edit/'
            preLoaderRoute: typeof DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRouteImport
            parentRoute: typeof DataServiceConfigurationProviderConfigIdProviderEditProviderRoute
        }
    }
}

interface DataServiceConfigurationProviderConfigIdProviderEditProviderRouteChildren {
    DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute: typeof DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute
}

const DataServiceConfigurationProviderConfigIdProviderEditProviderRouteChildren: DataServiceConfigurationProviderConfigIdProviderEditProviderRouteChildren =
    {
        DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute:
            DataServiceConfigurationProviderConfigIdProviderEditProviderIndexLazyRoute,
    }

const DataServiceConfigurationProviderConfigIdProviderEditProviderRouteWithChildren =
    DataServiceConfigurationProviderConfigIdProviderEditProviderRoute._addFileChildren(
        DataServiceConfigurationProviderConfigIdProviderEditProviderRouteChildren
    )

interface DataServiceConfigurationProviderConfigIdProviderRouteChildren {
    DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute: typeof DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute
    DataServiceConfigurationProviderConfigIdProviderEditProviderRoute: typeof DataServiceConfigurationProviderConfigIdProviderEditProviderRouteWithChildren
}

const DataServiceConfigurationProviderConfigIdProviderRouteChildren: DataServiceConfigurationProviderConfigIdProviderRouteChildren =
    {
        DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute:
            DataServiceConfigurationProviderConfigIdProviderIndexLazyRoute,
        DataServiceConfigurationProviderConfigIdProviderEditProviderRoute:
            DataServiceConfigurationProviderConfigIdProviderEditProviderRouteWithChildren,
    }

const DataServiceConfigurationProviderConfigIdProviderRouteWithChildren =
    DataServiceConfigurationProviderConfigIdProviderRoute._addFileChildren(
        DataServiceConfigurationProviderConfigIdProviderRouteChildren
    )

interface DataServiceConfigurationProviderRouteChildren {
    DataServiceConfigurationProviderIndexLazyRoute: typeof DataServiceConfigurationProviderIndexLazyRoute
    DataServiceConfigurationProviderConfigIdProviderRoute: typeof DataServiceConfigurationProviderConfigIdProviderRouteWithChildren
    DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute: typeof DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute
}

const DataServiceConfigurationProviderRouteChildren: DataServiceConfigurationProviderRouteChildren =
    {
        DataServiceConfigurationProviderIndexLazyRoute:
            DataServiceConfigurationProviderIndexLazyRoute,
        DataServiceConfigurationProviderConfigIdProviderRoute:
            DataServiceConfigurationProviderConfigIdProviderRouteWithChildren,
        DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute:
            DataServiceConfigurationProviderConfigIdValidationLogsIndexLazyRoute,
    }

const DataServiceConfigurationProviderRouteWithChildren =
    DataServiceConfigurationProviderRoute._addFileChildren(
        DataServiceConfigurationProviderRouteChildren
    )

const rootRouteChildren: RootRouteChildren = {
    IndexLazyRoute: IndexLazyRoute,
    DataServiceConfigurationProviderRoute:
        DataServiceConfigurationProviderRouteWithChildren,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
